### ISSUE TITLE
Please kindly prepare a readme

### ISSUE THREAD

**Issue by jalasem** [ooade/react-rough#1]

**Comment by ooade** [comment]
Yeah, i will. Definitely... I didn't write one because things are still a lil bit shaky for now; the API is much more likely to change, i'll probably test components with jest cos snapshots are lovely :heart_eyes:, so i'm taking down mocha and fam...

I'll leave this issue open with the `work in progress` label so as to keep bugging me to speed up things.

**Comment by ooade** [comment]
Thanks @jalasem We now have a readme
