### ISSUE TITLE
Error: Invalid key "x1" assigned to "line component"

### ISSUE THREAD

**Issue by fabmeyer** [ooade/react-rough#242]
I am not able to use the line type of components (line, linearpath, etc.)

Example code:

```
 render() {
    return (
      <div>
        <ReactRough width={120} height={180}>
          <Circle
            points={[60, 40, 40]}
            fill={this.props.color}
            fillWeight="6"
            fillStyle="hachure"
            strokeWidth="2"
            roughness="2"
            bowing="1"
          />
          <Rectangle
            points={[55, 60, 10, 80]}
            fill={this.props.color}
            fillWeight="6"
            fillStyle="hachure"
            strokeWidth="2"
            roughness="2"
            bowing="0"
          />
          <Line x1={80} x2={300} y1={120} y2={100} />
        </ReactRough>
      </div>
    );
  }
```

Circle and rectangle get rendered normally but the line doesn't. It throws an error.
Please help.

Edit: I ended up using the same coordinate description as in the circle and rectangle component:
`<Line points={[55, 100, 10, 80]} />` and that works perfect.

**Comment by ooade** [comment]
Hi @fabmeyer Please, can you state the version of react-rough you're using?

**Comment by fabmeyer** [comment]
Hi, @ooade my version is 2.0.0-beta.4. I assume this is the problem?

**Comment by ooade** [comment]
Yeah @fabmeyer. Version 2.0.0-beta.4 uses points so, it doesn't maintain rough's signatures. And, it might not be clear as to what kind of prop it takes and all.

Version 2.0.0 shipped in with intellisense because, it was built with TypeScript and, you could check out the type definition files to see the type of prop each Rough Component takes. You could also use the [Storybook](https://react-rough.dev.adegbuyi.me) as a Playground or reference when you need anything.
